name: pixelpal
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.31.1
  cloud_firestore: ^4.17.4
  firebase_auth: ^4.19.6
  firebase_storage: ^11.7.6
  fluttertoast: ^8.2.5
  font_awesome_flutter: ^10.1.0
  google_sign_in: ^6.2.1
  youtube_player_flutter: ^8.0.0
  cupertino_icons: ^1.0.6
  http: any
  google_ml_kit: ^0.18.0
  image_picker: ^0.8.5+3
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
