name: pixelpal
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.31.1
  cloud_firestore: ^4.17.4
  firebase_auth: ^4.19.6
  firebase_storage: ^11.7.6
  fluttertoast: ^8.2.5
  font_awesome_flutter: ^10.1.0
  google_sign_in: ^6.2.1
  youtube_player_flutter: ^8.0.0
  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  http: any
  google_ml_kit: ^0.18.0
  image_picker: ^0.8.5+3
  image_cropper: ^7.1.0
  shared_preferences: ^2.0.15
  intl: ^0.19.0
  firebase_auth_mocks: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.4
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logo_dark.png
    - assets/images/logo app light blue background.png
    - assets/images/logo app transparent background.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/images/logo app light blue background.png"
  min_sdk_android: 24
  remove_alpha_ios: true
